'use strict';

const bullshit = [
  '24/365',
  '24/7',
  'accelerate',
  'accountability',
  'action items',
  'action-items',
  'actionable',
  'aggregate',
  'aggregator',
  'agile',
  'algorithm',
  'alignment',
  'analytics',
  'applications',
  'architect',
  'architectures',
  'at the end of the day',
  'B2B',
  'B2C',
  'back-end',
  'bandwidth',
  'below the fold',
  'benchmark',
  'best of breed',
  'best practices',
  'best-of-breed',
  'beta',
  'big data',
  'bleeding edge',
  'bleeding-edge',
  'blueprint',
  'boil the ocean',
  'bottom line',
  'bounce rate',
  'brand evangelist',
  'brand',
  'bricks and clicks',
  'bricks-and-clicks',
  'bring to the party',
  'bring to the table',
  'brogrammer',
  'capital',
  'change agent',
  'channels',
  'clicks-and-mortar',
  'clickthrough',
  'close the loop',
  'codify',
  'collaboration',
  'collaborative',
  'collateral',
  'come to Jesus',
  'communities',
  'compelling',
  'content strategy',
  'content',
  'convergence',
  'coopetition',
  'create value',
  'credibility',
  'cross the chasm',
  'cross-media',
  'cross-platform',
  'crowdfund',
  'crowdsource',
  'cultivate',
  'curate',
  'customized',
  'cutting-edge',
  'data mining',
  'deep dive',
  'deliver',
  'deliverables',
  'democratize',
  'deploy',
  'design pattern',
  'digital divide',
  'digital natives',
  'discovery',
  'disintermediate',
  'disruptive',
  'distributed',
  'diversity',
  'DNA',
  'do more with less',
  'dot-com',
  'downsizing',
  'drink the Kool Aid',
  'drive',
  'DRM',
  'dynamic',
  'e-business',
  'e-commerce',
  'e-enable',
  'e-markets',
  'e-services',
  'e-tailers',
  'eat your own dog food',
  'efficient',
  'embrace',
  'emerging',
  'empathy',
  'empower',
  'enable',
  'end-to-end',
  'engage',
  'engagement',
  'engaging',
  'engineer',
  'enhance',
  'enterprise',
  'entitled',
  'envisioneer',
  'epic',
  'evangelist',
  'evolve',
  'exchanges',
  'exit strategy',
  'expedite',
  'experiences',
  'exploit',
  'extend',
  'extensible',
  'eyeballs',
  'face time',
  'facilitate',
  'fail fast',
  'fail forward',
  'fanboy',
  'finalize',
  'first or best',
  'flat',
  'flow',
  'freemium',
  'frictionless',
  'front-end',
  'functionalities',
  'funded',
  'funnel',
  'fusion',
  'game changer',
  'gameify',
  'gamification',
  'generate',
  'glamour metrics',
  'global',
  'globalization',
  'granular',
  'green',
  'groupthink',
  'grow',
  'growth hack',
  'guru',
  'harness',
  'headlights',
  'heads down',
  'herding cats',
  'high level',
  'holistic',
  'homerun',
  'html5',
  'hyperlocal',
  'iconic',
  'ideation',
  'ignite',
  'immersive',
  'impact',
  'impactful',
  'implement',
  'impressions',
  'in the weeds',
  'incentivize',
  'incubate',
  'infographic',
  'infomediaries',
  'infrastructures',
  'initiatives',
  'innovate with',
  'innovate',
  'innovative',
  'integrate',
  'integrated',
  'interactive',
  'interfaces',
  'intuitive',
  'iterate on',
  'jellyfish',
  'killer',
  'knee deep',
  'leading-edge',
  'lean in',
  'lean',
  'level up',
  'leverage',
  'lizard brain',
  'long tail',
  'low hanging fruit',
  'magnetic',
  'make it pop',
  'make the logo bigger',
  'maker',
  'marketing funnel',
  'markets',
  'mashup',
  'maximize',
  'mesh with',
  'methodologies',
  'metrics',
  'milestone',
  'mindshare',
  'mission-critical',
  'models',
  'modernity',
  'monetize',
  'morph',
  'moving forward',
  'MVP',
  'netiquette',
  'networks',
  'next gen',
  'next level',
  'next-generation',
  'niches',
  'ninja',
  'offshoring',
  'on the runway',
  'one-to-one',
  'open the kimono',
  'open-source',
  'operationalize',
  'opportunity',
  'optimize',
  'orchestrate',
  'organic',
  'out of pocket',
  'out-of-the-box',
  'outside the box',
  'outsourcing',
  'over the top',
  'paradigm shift',
  'paradigms',
  'partnerships',
  'patent pending design',
  'patent',
  'peeling the onion',
  'ping',
  'pipeline',
  'pivot',
  'platforms',
  'plug-and-play',
  'pop',
  'portal',
  'portals',
  'proactive',
  'productize',
  'proof of concept',
  'public facing',
  'pull the trigger',
  'push the envelope',
  'qualified leads',
  'reach out',
  'real time',
  'real-time',
  'recontextualize',
  'redefine',
  'reimagining',
  'reintermediate',
  'reinvent the wheel',
  'reinvent',
  'relationships',
  'repurpose',
  'responsive',
  'revolutionary',
  'revolutionize',
  'rich',
  'rightshoring',
  'rightsizing',
  'robust',
  'rockstar',
  'ROI',
  'scalability',
  'scalable',
  'scale',
  'schemas',
  'scratch your own itch',
  'scrum',
  'sea change',
  'seamless',
  'seize',
  'SEM',
  'SEO',
  'sexy',
  'shift',
  'sizzle',
  'slam dunk',
  'social currency',
  'social media expert',
  'social media',
  'social proof',
  'social-media',
  'social',
  'soft launch',
  'solution',
  'solutions',
  'stakeholder',
  'standup',
  'startup',
  'stealth mode',
  'stealth startup',
  'sticky',
  'storytelling',
  'strategery',
  'strategic',
  'strategize',
  'strategy',
  'streamline',
  'supply-chains',
  'sustainability',
  'sweat your assets',
  'sync on',
  'syndicate',
  'synergies',
  'synergistic',
  'synergize',
  'synergy',
  'synthesize',
  'systems',
  'take it offline',
  'target',
  'team building',
  'technologies',
  'tee off',
  'the cloud',
  'thought leader',
  'tiger team',
  'tollgate',
  'top of mind',
  'touch base',
  'touchpoints',
  'transform',
  'transgenerate',
  'transition',
  'transparent',
  'trickthrough',
  'turn-key',
  'uber',
  'ubiquitous',
  'unicorn',
  'uniques',
  'unleash',
  'unpack',
  'user-centric',
  'user',
  'usercentric',
  'users',
  'utilize',
  'value proposition',
  'value-added',
  'vertical',
  'viral',
  'virtual',
  'visibility',
  'vision',
  'visionary',
  'visualize',
  'vortals',
  'web services',
  'web-enabled',
  'web-readiness',
  'webinar',
  'what is our solve',
  'whiteboard',
  'wireless',
  'wizard',
  'world-class'
];

module.exports = {
  bullshit
};
